version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "00:00"
    open-pull-requests-limit: 5
    reviewers:
      - aarush0101
    assignees:
      - aarush0101
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "00:00"
    open-pull-requests-limit: 15
    reviewers:
      - aarush0101
    assignees:
      - aarush0101
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
