version: "3.9"

services:
  zendo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zendo
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    networks:
      - zendo-network

networks:
  zendo-network:
    driver: bridge
