services:
  zendo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zendo
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    networks:
      - zendo-network

  nginx:
    image: nginx:stable-alpine
    container_name: zendo-proxy
    ports:
      - "3000:80"
    volumes:
      - ./nginx.conf.template:/etc/nginx/nginx.conf.template:ro
      - ./nginx-entrypoint.sh:/docker-entrypoint.sh:ro
    depends_on:
      - zendo
    environment:
      - NGINX_URL=${NGINX_URL}
    networks:
      - zendo-network

networks:
  zendo-network:
    driver: bridge
